# Generated by Django 5.0 on 2024-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowID', models.CharField(max_length=50, unique=True)),
                ('srcIP', models.CharField(max_length=20)),
                ('dstPort', models.CharField(max_length=50)),
                ('fwdFlags', models.CharField(max_length=25)),
                ('bwdFlags', models.CharField(max_length=25)),
                ('fwdTimeDelta', models.CharField(max_length=15)),
                ('bwdTimeDelta', models.CharField(max_length=15)),
                ('fwdWindowSize', models.CharField(max_length=25)),
                ('bwdWindowSize', models.CharField(max_length=25)),
                ('protocol', models.CharField(max_length=10)),
                ('fwdMeanDelta', models.CharField(max_length=25)),
                ('bwdMeanDelta', models.CharField(max_length=25)),
                ('fwdVarianceDelta', models.CharField(max_length=25)),
                ('bwdVarianceDelta', models.CharField(max_length=25)),
                ('fwdStdDevDelta', models.CharField(max_length=25)),
                ('bwdStdDevDelta', models.CharField(max_length=25)),
                ('synFlag', models.CharField(max_length=25)),
                ('ackFlag', models.CharField(max_length=25)),
                ('rstFlag', models.CharField(max_length=25)),
                ('pshFlag', models.CharField(max_length=25)),
                ('finFlag', models.CharField(max_length=25)),
                ('urgFlag', models.CharField(max_length=25)),
                ('cwrFlag', models.CharField(max_length=25)),
                ('eceFlag', models.CharField(max_length=25)),
                ('FwdPacketByteRate', models.CharField(max_length=25)),
                ('BwdPacketByteRate', models.CharField(max_length=25)),
                ('fwdPayloadSize', models.CharField(max_length=25)),
                ('bwdPayloadSize', models.CharField(max_length=25)),
                ('fwdFlowPacketRate', models.CharField(default=1, max_length=25)),
                ('bwdFlowPacketRate', models.CharField(default=1, max_length=25)),
                ('fwdPayloadVariance', models.CharField(max_length=25)),
                ('bwdPayloadVariance', models.CharField(max_length=25)),
                ('fwdPacketCount', models.CharField(max_length=50)),
                ('bwdPacketCount', models.CharField(max_length=50)),
                ('packetCount', models.CharField(max_length=50)),
                ('totalFwdByteCount', models.CharField(max_length=50)),
                ('totalBwdByteCount', models.CharField(max_length=50)),
                ('fwdFlowDuration', models.CharField(max_length=50)),
                ('bwdFlowDuration', models.CharField(max_length=50)),
                ('fwdMeanByteSize', models.CharField(max_length=50)),
                ('bwdMeanByteSize', models.CharField(max_length=50)),
                ('fwdStDevByteSize', models.CharField(max_length=50)),
                ('bwdStDevByteSize', models.CharField(max_length=50)),
                ('fwdVarianceByteSize', models.CharField(max_length=50)),
                ('bwdVarianceByteSize', models.CharField(max_length=50)),
                ('rtt', models.CharField(max_length=15)),
                ('Label', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('previousTimestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
