# Generated by Django 5.0 on 2024-01-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='fwdUniquePorts',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
