# Generated by Django 5.0 on 2024-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0006_flow_authfailures'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrequentOrigin', models.CharField(max_length=10)),
            ],
        ),
    ]
