# Generated by Django 5.0 on 2024-02-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0007_flowstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstatistics',
            name='FrequentAttack',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowstatistics',
            name='FrequentOrigin',
            field=models.JSONField(),
        ),
    ]
