# Generated by Django 5.0 on 2024-02-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0010_alter_flowstatistics_frequentorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstatistics',
            name='FrequentOrigin',
            field=models.JSONField(verbose_name='killenaule'),
        ),
    ]
