# Generated by Django 5.0 on 2024-02-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0011_alter_flowstatistics_frequentorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstatistics',
            name='FrequentOrigin',
            field=models.JSONField(),
        ),
    ]
