# Generated by Django 5.0 on 2024-02-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0012_alter_flowstatistics_frequentorigin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstatistics',
            name='FrequentAttack',
        ),
        migrations.RemoveField(
            model_name='flowstatistics',
            name='FrequentOrigin',
        ),
        migrations.AddField(
            model_name='flowstatistics',
            name='Testing',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
