# Generated by Django 5.0 on 2024-02-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0013_remove_flowstatistics_frequentattack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstatistics',
            name='Testing',
        ),
        migrations.AddField(
            model_name='flowstatistics',
            name='FrequentAttack',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowstatistics',
            name='FrequentOrigin',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
