# Generated by Django 5.0 on 2024-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0014_remove_flowstatistics_testing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='Origin',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
