# Generated by Django 5.0 on 2024-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0018_tfmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='ackFlag',
            new_name='Backward0x0014Flag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='cwrFlag',
            new_name='Backward0x003FFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='eceFlag',
            new_name='BackwardAckFinPshFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='finFlag',
            new_name='BackwardAckFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='pshFlag',
            new_name='BackwardAckPshFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='rstFlag',
            new_name='BackwardFinAckFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='synFlag',
            new_name='BackwardFinFlag',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='urgFlag',
            new_name='BackwardRstFlag',
        ),
        migrations.AddField(
            model_name='flow',
            name='BackwardSynAckFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='BackwardSynFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='BackwardUrgFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='Forward0x0014Flag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='Forward0x003FFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardAckFinPshFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardAckFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardAckPshFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardFinAckFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardFinFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardRstFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardSynAckFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardSynFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='ForwardUrgFlag',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
