# Generated by Django 5.0 on 2024-03-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0019_rename_ackflag_flow_backward0x0014flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='BackwardSynFlag',
        ),
    ]
