# Generated by Django 5.0 on 2024-03-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDPBackend', '0022_rename_flowid_flow_forward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingstatus',
            name='status',
        ),
    ]
